name: DocC
on:
  push:
    branches:
      - main
jobs:
  BuildDocC:
    runs-on: macos-latest
    steps:
      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: "6.0"
      - uses: actions/checkout@v4
      - name: Build DocC
        run: |
          swift package --allow-writing-to-directory ./docs generate-documentation \
          --target SGFKit \
          --disable-indexing \
          --output-path ./docs \
          --transform-for-static-hosting \
          --hosting-base-path SGFKit \
          --source-service github \
          --source-service-base-url https://github.com/mtj0928/SGFKit/blob/main \
          --checkout-path $GITHUB_WORKSPACE
        env:
          DOCC_BUILD: 1
      - uses: actions/upload-pages-artifact@v3
        id: docs
        with:
          path: docs
  DeployDocC:
    needs: BuildDocC
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: docs
        uses: actions/deploy-pages@v4
